name: Test Runner Connectivity

on:
  workflow_dispatch:

jobs:
  test-connectivity:
    runs-on: ubuntu-latest

    steps:
      # 測試是否能連線到 GitHub API
      - name: Test GitHub API connectivity
        run: curl -I https://api.github.com

      # 測試是否能下載 Actions 資源
      - name: Test Actions resource connectivity
        run: curl -I https://pkg.actions.githubusercontent.com
