name: Print Repo Info

on:
  workflow_dispatch:

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      # 檢出儲存庫
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 打印完整儲存庫名稱（包含擁有者）
      - name: Print Full Repository Name
        run: echo "${{ github.repository }}"

      # 提取僅儲存庫名稱（不包含擁有者）
      - name: Extract Repository Name
        run: echo "${{ github.repository }}" | awk -F'/' '{print $2}'

      # 打印工作目錄路徑
      - name: Print Working Directory
        run: pwd

      # 打印儲存庫文件列表
      - name: List Repository Files
        run: ls -la
